### ISSUE TITLE
Hi, I stumbled upon this toolkit by chance. Can I ask a few questions?

### ISSUE THREAD

**Issue by StarSkyK** [chsxf/CiderKit#13]
Hi, I stumbled upon this toolkit by chance. Can I ask a few questions?

1. Is development currently in progress?
2.What is the goal of this toolkit? Is it possible to achieve something similar to Unity2D?

Thank you for your open-source code.

**Comment by chsxf** [comment]
Hi

Thank you for your interest in CiderKit.

1. Yes, development is currently in progress. The last commit is from a week ago or so. And it is very very early. Not reeady for production or probably for use with others without a lot of modifications.
2. The goal of CiderKit is to serve as a game engine on top of SpriteKit to accelerate the production of my games (and eventually those of others). Even if it is not a mandatory goal, ultimately, probably not before many years, it should be versatile enough to do things like you would in Unity2D but with less features obviously (solo dev here).

**Comment by StarSkyK** [comment]
I'm looking forward to it.😊
